# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f7f1f290593444af867f919f52abb55d2cc4dc0481b16cac2d6c1e196dd7ca4df856e85c644e6d4e99670eeba8f06fe75508e5a8548c88b51527dcb4e3e2189

test:
  secret_key_base: f2f0db946ad1d5544af637d21f4e3325343ccd87b1c1b80b0e85bb65ff1eb4690b334bfebc8c71d5c2eeb38b5b76a14bee7d9e3cae19809de531dfa7e77edfe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
